# Generated by Django 5.1.6 on 2025-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
