# Generated by Django 5.1.6 on 2025-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_uploaded_at_resume_extracted_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('skills', models.JSONField()),
                ('experience', models.FloatField()),
                ('job_title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('rejection_reason', models.TextField()),
            ],
        ),
    ]
