# Generated by Django 5.1.6 on 2025-02-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_candidate_experience_alter_candidate_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_title',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='score',
            field=models.FloatField(),
        ),
    ]
